---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-lazztechhub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-lazztechhub
  template:
    metadata:
      labels:
        app: dev-lazztechhub
    spec:
      containers:
        - name: dev-lazztechhub
          image: registry.internal.lazz.tech/dev-lazztechhub-service
          env:
            - name: APP_NAME
              value: "Lazztech Hub"
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: access-token-secret
            - name: FIREBASE_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: firebase-server-key
            - name: PUSH_NOTIFICATION_ENDPOINT
              value: https://fcm.googleapis.com/fcm/send
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: google-client-id
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: google-secret
            - name: EMAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: email-from-address
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: email-password
            - name: DATABASE_HOST
              value: localhost
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: database-pass
            - name: DATABASE_SCHEMA
              value: postgres
            - name: DATABASE_SSL
              value: "false"
            - name: FILE_STORAGE_TYPE
              value: object
            - name: OBJECT_STORAGE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: object-storage-access-key-id
            - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: object-storage-secret-access-key
            - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
              value: nyc3.digitaloceanspaces.com
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "750m"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
        - name: dev-lazztechhub-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-lazztechhub
                  key: database-pass
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5432
          volumeMounts:
          - mountPath: /var/lib/postgresql
            name: postgres-data
          imagePullPolicy: IfNotPresent
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: dev-lazztechhub-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-lazztechhub-pvc
  namespace: default
  labels:
    app: dev-lazztechhub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dev-lazztechhub-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: dev-lazztechhub
---
apiVersion: v1
kind: Service
metadata:
  name: dev-lazztechhub-db-service
  labels:
    app: dev-lazztechhub
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: tcp
  selector:
    app: dev-lazztechhub-db
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dev-lazztechhub-lazztech-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - secretName: lazztech-acme-crt-secret
      hosts:
        - '*.lazz.tech'
  rules:
  - host: dev-lazztechhub.lazz.tech
    http:
      paths:
      - backend:
          serviceName: dev-lazztechhub-service
          servicePort: 80