name: Github Actions CI
on: [push]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  back-end-ci:
    name: back-end-ci
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@master

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install & build
      run: |
        npm install
        npm run build
  
    - name: npm format:check
      run: |
        npm run format:check
  
    - name: npm lint
      run: |
        npm run lint

    - name: npm test:cov
      run: |
        npm run test:cov

    - name: npm test:e2e
      run: |
        npm run test:e2e
      env:
        CI: true
        ACCESS_TOKEN_SECRET: SecretKey

    - name: npm start & health check
      # 'nohup npm run start:prod >> app.log 2>&1 &' runs the command as a background job: https://stackoverflow.com/a/46732894/848396
      # 'timeout 30 bash -c 'until echo > /dev/tcp/localhost/13000; do sleep 0.5; done' wait for server to start up or timeout with error: https://unix.stackexchange.com/a/349138
      # 'kill %1' kills background job: https://unix.stackexchange.com/a/104822
      run: |
        nohup npm run start:prod >> app.log 2>&1 &
        timeout 30 bash -c 'until echo > /dev/tcp/localhost/8080; do sleep 0.5; done'
        kill %1
      env:
        CI: true
        ACCESS_TOKEN_SECRET: SecretKey

  # deploy:
  #   name: deploy-cd-master
  #   runs-on: ubuntu-latest
  #   needs: back-end-ci
  #   if: github.ref == 'refs/heads/master'
  #   steps:

  #   - uses: actions/checkout@master

  #   - name: Use Node.js ${{ env.NODE_VERSION }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ env.NODE_VERSION }}

  #   - name: npm install & build
  #     run: |
  #       npm install
  #       npm run build
