name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
        postgresql db: 'postgres-test'
        postgresql user: 'test'
        postgresql password: 'Password123'
    - name: npm install, build, and test
      working-directory: ./serverless
      run: |
        npm install
        # npm ci
        # npm run build --if-present
        npm test
      env:
        CI: true
